### ISSUE TITLE
[Feature Request]: for emby

### ISSUE THREAD

**Issue by xinmans** [tubearchivist/tubearchivist-jf-plugin#14]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

https://github.com/xinmans/tubearchivist-emby

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by DarkFighterLuke** [comment]
Hi @xinmans , I'm happy that you will work on that, but I think that it would be better if you create a separate codebase in a specific repository, let's leave this for Jellyfin only.

**Comment by xinmans** [comment]
> Hi @xinmans , I'm happy that you will work on that, but I think that it would be better if you create a separate codebase in a specific repository, let's leave this for Jellyfin only.

thanks， that's ok
