### ISSUE TITLE
[Bug]: API Call Forbidden

### ISSUE THREAD

**Issue by ironlion27** [tubearchivist/tubearchivist-jf-plugin#20]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux, Docker Compose

## Describe the bug
No metadata pulled from the TA scraper just coded folder names and files.

## Steps To Reproduce
Install fresh as the documentation described.  First pull of video metadata into Jellyfin.  Have docker compose pulled.  Everything is the most updated.  The TA site works great.  The http://192.168.1.104:7400/api/video/rB306klRlKA/ page works in browser fine with api response.  Double checked I have correct API key from TA site input to the Jellyfin Plugin settings.

## Expected behavior
Same info returned as API call through Browser:
HTTP 200 OK
Allow: GET, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "data": {
        "active": true,
        "category": [
            "Science & Technology"
        ],
        "channel": {
            "channel_active": true,
            "channel_banner_url": "/cache/channels/UCzIO0iX4yKW2P4NkmmKq1PA_banner.jpg",
            "channel_description": "9to5Google covers the latest in Google. Specifically, we focus on Android, Google Pixel, Google Home (Hub, Mini, Max, and more!), Chromebooks, Google Pixel Slate, Pixelbook, the latest handsets from the various Android OEMs, and much more.",
            "channel_id": "UCzIO0iX4yKW2P4NkmmKq1PA",
            "channel_last_refresh": "2024-07-22",
...

### Relevant Jellyfin log output

```shell
[2024-07-22 23:02:59.313 +00:00] [INF] [61] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "http://192.168.1.104:7400/api/video/rB306klRlKA/: Forbidden"
[2024-07-22 23:02:59.313 +00:00] [INF] [61] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting images for video:  (rB306klRlKA)"
[2024-07-22 23:02:59.313 +00:00] [INF] [61] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Thumb URI: "
```

**Comment by fiveghz** [comment]
I ran into the exact same behavior and suspected it was not sending the API token in the request, hence the 403 Forbidden.  I ended up removing the trailing slash from the `TubeArchivist URL` in the Jellyfin plugin settings and then it started working.  To test, I added the slash back in, but it seemed to continue working so 🤷‍♂️

**Comment by JoshNotWright** [comment]
Running into this issue as well. Tried to remove the trailing slash as @fiveghz suggested, but unfortunately this didn't work for me.

**Comment by JoshNotWright** [comment]
> Running into this issue as well. Tried to remove the trailing slash as @fiveghz suggested, but unfortunately this didn't work for me.

Not sure if it's related, but I had downloads in progress on TA and stopped them. Restarted Jellyfin and now it's refreshing metadata just fine.

**Comment by DarkFighterLuke** [comment]
Not a plugin bug. Check the other similar closed issues.
