### ISSUE TITLE
[Feature request]: Ping the TA API to validate connection

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist-jf-plugin#3]
When setting up the TubeArchivist URL and API key, it would be convenient to send a PING request to `/api/ping/`, if that responds with 200, I'll know I entered my connection details correctly. 

Otherwise only the logs will show when indexing if something isn't working.

**Comment by DarkFighterLuke** [comment]
Hi @bbilly1 , I've already thought of that and we could just implement it. However, I think you will only see the output of the check from the Jellyfin logs, but I will investigate.

**Comment by DarkFighterLuke** [comment]
Just to confirm, I've checked with the Jellyfin guys and they confirmed what I knew, there is no chance to send notifications on the UI from a plugin, so I will only put the ping result in the logs.

**Comment by DarkFighterLuke** [comment]
Implementation has been done and released https://github.com/tubearchivist/tubearchivist-jf-plugin/releases/tag/v1.2.5.
