### ISSUE TITLE
Handle trailing / in URL

### ISSUE THREAD

**Issue by p-rintz** [tubearchivist/tubearchivist-jf-plugin#4]
This is kind of related to #3 , but the Plugin does not handle having a trailing / at the end of the Tubearchivist URL.

This leads to errors and the plugin silently failing (hence the relation to #3 )

I have no preference how this gets handled.
Could be a notice to not include it, handling it in code or throwing an error.

**Comment by ThisIsHetz** [comment]
Prefacing this with my usual disclaimer of "I'm not a dev", PluginConfiguration.cs calls to Utils.cs for `SanitizeUrl()` to sanitize the value provided for `_tubeArchivistUrl` (the variable for the field where your TA URL goes in the plugin form):

```csharp
public static string SanitizeUrl(string inputURL)
{
...
  cleanedPath = cleanedPath.TrimStart('/');
  cleanedPath = cleanedPath.TrimEnd('/') + "/";
...
```

Assuming I understand all of the above correctly, `SanitizeUrl()` explicitly adds a trailing forward slash in the event one isn't included. It actually removes all trailing forward slashes, if any are included, before appending just one; akin to a `cleanedPath = cleanedPath.rstrip('/') + "/"` in Python.

That the plugin actually forces a trailing slash, in combination with a "works on my machine" (I included a slash, when configuring the plugin, without issue), makes me wonder if this could be a symptom of another issue.

**Comment by p-rintz** [comment]
Hm. Not entirely sure. The issue showed itself on my side as permission denied errors or the like, and the only thing I changed, before it started working, was the trailing slash in the plugin config, so I assumed that it was that.

Not sure what else it would be.

**Comment by p-rintz** [comment]
If you cant reproduce it on your side, Ill just close this issue for now and reopen a new one if I can find out what else it was that made it not work. Thanks for your help.
