### ISSUE TITLE
[Feature request]: Send watch state to TA. 

### ISSUE THREAD

**Issue by xusiai** [tubearchivist/tubearchivist-jf-plugin#7]
Would it be feasible to add support for sending watched state to TubeArchivist? Since videos can be configured for automatic removal after being set to watched in TA it would be nice if this feature continued to work when the actual media consumption is done in Jellyfin.

**Comment by ITSecUK** [comment]
I would also be really keen on this! I was thinking it might be possible to adapt an existing jellyfin music scrobble plugin such as: https://github.com/lyarenei/jellyfin-plugin-listenbrainz but I have not yet had time to look into this further, and dont have experience with C# but just wanted to note down the idea incase anyone else is more familiar with that!

**Comment by diablo581** [comment]
>  I might just start deleting in Jellyfin after watching, then set a cron for TA to update its metadata (cant set that cron in the settings page).

Can you elaborate on this some please? This is kind of my use case.

**Comment by ITSecUK** [comment]
@diablo581 I ended up going a different way and I just use the TA interface instead, the only downside of that is I cant watch on my TV easily.

Under settings > actions there is an option "Rescan filesystem" which will clean up any deleted files, but there are two things I didnt get around to finding out:

1. If you delete a video, I didn't confirm that its not re-added next time TA scans the channel (hopefully not)
2. how you can best call that endpoint from cron.

You can either figure out if you can add a new task somehow similar to how the app does it here:
https://github.com/tubearchivist/tubearchivist/blob/24b57406ab9700be73eaa900b3920526337ef161/tubearchivist/config/management/commands/ta_startup.py#L261

Or worst case you could just hit the API /api/task-name/rescan_filesystem/
as the webapp does:
https://github.com/tubearchivist/tubearchivist/blob/24b57406ab9700be73eaa900b3920526337ef161/tubearchivist/static/script.js#L488

Good luck!!

**Comment by DarkFighterLuke** [comment]
@ITSecUK your use case has little to do with the main feature request, it's a particular use case not even specifically related to this plugin.
