### ISSUE TITLE
[Bug]: api returns Forbidden in jellyfin

### ISSUE THREAD

**Issue by BigGDeX** [tubearchivist/tubearchivist-jf-plugin#9]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

debian

## Describe the bug
When the plugin send a request to the tubearchivist server, it gets a Forbidden as response. If I copy paste the request url into the browser I get a Django page whit the response. I used the admin account api key on the plugin configuration. It seems like it's sending the wrong key maybe? Or I missed some step on configuring jellyfin and tubearchivist?
### Relevant Jellyfin log output

```shell
[13:25:50] [INF] [86] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: Getting metadata for channel:  (UC-ciXrv4h_IE3ga1dMfTUdA)
[13:25:50] [INF] [86] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: Received metadata: 
null
[13:25:50] [INF] [86] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: http://10.1.1.5:8967/api/channel/UC-ciXrv4h_IE3ga1dMfTUdA/: Forbidden
```

**Comment by BigGDeX** [comment]
I recreated the jellyfin Youtube library after a restart and it now works, awesome!

**Comment by DarkFighterLuke** [comment]
Hi @BigGDeX , unfortunately it is a Jellyfin problem, it seems not reading the configuration properly some times and you need to reload the Dashboard page or restart the Jellyfin server.

Happy you found the solution by yourself :)

**Comment by wpisarski** [comment]
Unfortunately, no combination of restarting and recreating the library helps for me, I still get "Forbidden" error. Is there anything other I can try to make it work?
